### ISSUE TITLE
add_attribute/dedupe_lookups not working

### ISSUE THREAD

**Issue by gabrielnewrelic** [newrelic/nri-flex#177]
hey, i tried almost all features under the Data parsing and transformation functions. I was unable to make either add_attribute or dedupe_lookups to work. I ended up using custom_attributes instead of add_attribute, so not too worry about that one. But dedupe_lookup will come in very handy, this is how I was trying to use it:
- event_type: JenkinJobsLookup
   url: /api/json?tree=jobs[name]
   store_lookups:
    name: name
 - event_type: Jenkins
   url: /job/${lookup:name}/wfapi/runs
   dedupe_lookups:
    - name

**Comment by Kav91** [comment]
Hey @gabrielnewrelic, `dedupe_lookups` is available to the new native lookups.
In the info about that feature the hyperlink refers to this implementation here -> https://github.com/newrelic/nri-flex/blob/master/docs/basics/functions.md#lookups

Your example is using a lookup generated from `store_lookups`. This is now simplified with the doc mentioned.

`add_attribute` is for building new attributes from existing attributes, the functionality is different to `custom_attributes`.

eg.
```yaml
integrations:
  - name: nri-flex
    interval: 30s
    config:
      name: addTest
      apis:
        - url: https://jsonplaceholder.typicode.com/users/1
          add_attribute:
            newAttr: myNewAttr_${name}_${username}_${email}
```

I don't believe there is any issue here, but we should improve the docs to direct users to look at the new lookup feature first. Let me know if that all makes sense or if there is still any issues.
