### ISSUE TITLE
Powershell integration not respecting set timeout

### ISSUE THREAD

**Issue by nrim** [newrelic/nri-flex#254]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I have a windows integration that returns some software versions.  On hosts where this takes less than 10 seconds, it's fine, but if it takes longer than 10 seconds, the flex integration returns `exit code 1`.  I have tried increasing the timeout but regardless of the value used, the integration fails after 10 seconds

## Expected Behavior

The timeout value is respected to support longer running integrations on windows

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[nri-flex_debug.log](https://github.com/newrelic/nri-flex/files/5691102/nri-flex_debug.log)

[pa-baseline_ps1.txt](https://github.com/newrelic/nri-flex/files/5691120/pa-baseline_ps1.txt)
[integration_yml.txt](https://github.com/newrelic/nri-flex/files/5691121/integration_yml.txt)

It seems the problem is with Get-SEPVersion.  On some hosts, it's fine, but in many cases `$SEPService=(Get-WmiObject -Class Win32_Product | Where-Object -FilterScript {$_.Name -eq "symantec endpoint protection"})` takes considerably longer due to additional software installed on the host

I've simplified it to run a powershell script that sleeps for 15 seconds and I get the same result

## Steps to Reproduce

1.  create a windows integration that takes longer than 10 seconds to return
2. execute the integration either with the infrastructure agent or using nri-flex.exe

--> should get `exit code 1` instead of results from the integration

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by nrim** [comment]
It looks like I may have been using the timeout incorrectly.  I had seen examples like this:

```
integrations:
  - name: nri-flex
    timeout: 30s
    config:
```

but it appears the timeout needs to go in the config itself in milliseconds like this

```
integrations:
  - name: nri-flex
    config:
      name: flexIntegrations
      apis:
        - name: baseline
          shell: powershell
          timeout: 90000
          commands:
            - run: "& \"C:/Program Files/New Relic/newrelic-infra/integrations.d/pa-baseline.ps1\""
```

I don't know if that's intended or not, but by switching to the second example, my integration worked.

**Comment by thezackm** [comment]
you've found an admittedly frustrating edge situation. 

essentially; there are 2 distinct parts of your config file. 

The upper portion belongs to our [Integrations SDK](), which the infrastructure agent uses to execute various integrations.  

```yaml
integrations:         # Start a config block for the Integrations SDK 
  - name: nri-flex    # Tell the Integrations SDK which binary to execute
    ...               # Insert other Intergrations SDK-specific parameters here...
    timeout: 30s      # Set your timeout value for the execution of the binary named above
    config:           # Provide a config that will be passed to the binary named above
```

And the lower portion is the actual configuration of the Flex integration itself:

```yaml
      ...
      name: flexIntegrations    # Name this config block (only used inside of this YAML)
      apis:                     # Start the block telling Flex which APIs are to be executed
        - name: baseline        # Name the event that will be generated for New Relic (NRDB) ***Note below
          shell: powershell     # Name the shell to execute the command(s) in
          timeout: 90000        # Specify the timeout value (ms) for the command(s) to execute in this config block
          commands:             # Start the block showing which command(s) to execute
            - run: ""           # Provide command(s) to execute
```

_***Note: For readability, you may consider using [event_type](https://github.com/newrelic/nri-flex/blob/310727f34538b7134112c66516e8d3f47dcfbeac/docs/basics/configure.md#apis) inside of your `apis` block. It's a preference item and not required._ 

So there are actually TWO `timeout` elements in a config like this. One for the [Integrations SDK](https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format#timeout) (default: 120s), and one specifically for the [Flex configuration](https://github.com/newrelic/nri-flex/blob/master/docs/apis/commands.md#specify-a-timeout) of the `commands` API (default: 10s). It's a rare thing to need to use them, but as you've seen, the 10s default for the `commands` API can be a tad too short in some circumstances. 

Hope this helps clear up any confusion!
