### ISSUE TITLE
Tutorial Doc example incorrect

### ISSUE THREAD

**Issue by haihongren** [newrelic/nri-flex#278]
In  https://github.com/newrelic/nri-flex/blob/master/docs/basic-tutorial.md

The following example is incorrect.  We need to remove 

```yaml
integrations:
  - name: nri-flex
    config:
      name: linuxFileSystemIntegration
      apis:
        - name: FileSystem
          commands:
            - run: 'df -PT -B1 -x tmpfs -x xfs -x vxfs -x btrfs -x ext -x ext2 -x ext3 -x ext4'
              split: horizontal
              split_by: \s+
              row_start: 1
              set_header: [fs,fsType,capacityBytes,usedBytes,availableBytes,usedPerc,mountedOn]
          perc_to_decimal: true
      name: linuxOpenFD
      apis:
        - name: linuxOpenFD
          commands:
            - run: cat /proc/sys/fs/file-nr | awk '{print $1-$2,$3}'
              split: horizontal
              set_header: [openFD,maxFD]
              regex_match: true
              split_by: (\d+)\s+(.*)
```

we should remove the extra lines:

```yaml
      name: linuxOpenFD
      apis:
```
