### ISSUE TITLE
${lookup.<EventType>:<Attribute>} function is broken

### ISSUE THREAD

**Issue by haihongren** [newrelic/nri-flex#280]
- The `${lookup.test1:payload}` usage in below example causes panic

```yaml
---
integrations:
  - name: nri-flex
    config:
      name: test1
      apis:
        - name: test1
          event_type: test1
          commands:
            - run: echo 'mydata'
              set_header: [payload]
              split: horizontal
              regex_match: true
              split_by: (.*)

        - name: test2
          commands:
            - run: echo "${lookup.test1:payload}"
```
