### ISSUE TITLE
add_attribute not working for commands

### ISSUE THREAD

**Issue by kidk** [newrelic/nri-flex#287]
## Description
I'm unable to get add_attribute working for commands. Example script below:

```
---
integrations:
  - name: nri-flex
    interval: 300s
    timeout: 300s
    config:
      name: WindowsScript
      apis:
        - event_type: SCOM
          shell: powershell
          commands:
            - run: "C:/Windows/system32/cscript.exe //nologo \"C:/Program Files/New Relic/newrelic-infra/integrations.d/files/LDAP_Bind_Availability.vbs\" 1  | & \"C:/Program Files/New Relic/newrelic-infra/integrations.d/files/xml2nr\""
              add_attribute:
                UnitMonitor: Microsoft.Windows.Server.2016.AD.Availability.Bind.Monitor
                Type: "Script"
```

I've also tried

```
---
integrations:
  - name: nri-flex
    interval: 300s
    timeout: 300s
    config:
      name: WindowsScript
      apis:
        - event_type: SCOM
          shell: powershell
          commands:
            - run: "C:/Windows/system32/cscript.exe //nologo \"C:/Program Files/New Relic/newrelic-infra/integrations.d/files/LDAP_Bind_Availability.vbs" 1  | \"C:/Program Files/New Relic/newrelic-infra/integrations.d/files/xml2nr\""
          add_attribute:
            UnitMonitor: Microsoft.Windows.Server.2016.AD.Availability.Bind.Monitor
            Type: "Script"
```

**Comment by haihongren** [comment]
@kidk 
`add_attribute` expect an existing attribute to be part of the  value: 

In the following example, `${id}` is an existing attribute. 
```yaml
    add_attribute:
      # use the 'id' attribute of the service output
      link: https://some-other-service/nodes/${id}
```

For your case, you can use `custom_attributes`:
```yaml
    custom_attributes:
         UnitMonitor: Microsoft.Windows.Server.2016.AD.Availability.Bind.Monitor
         Type: "Script"
```
