### ISSUE TITLE
Would love to see a trim function (right and left!) in a future Flex

### ISSUE THREAD

**Issue by haihongren** [newrelic/nri-flex#290]
## Is your feature request related to a problem? Please describe.
na

## Feature Description
Would love to see a `trim` function (right and left!) in a future Flex

## Describe Alternatives
`value_mapper` function can do this - need to use the following regex. 

```yaml
          value_mapper:
            field1:
              - ^\s*(.*?)\s*$=>$1
```

## Additional context
Add any other context here.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Really Want
