### ISSUE TITLE
Error with sample_exclude_filter

### ISSUE THREAD

**Issue by skirven4** [newrelic/nri-flex#328]
Hi,
   I'm trying to use a "sample_exclude_filter", and I keep getting the error: error="yaml: line 3: mapping values are not allowed in this context

My YAML is:

```
integrations:
- name: nri-flex
   interval: 300s
   config:
     name: ece_allocator_status
     apis:
       - event_type: ece_allocator_status
         url: <redacted>
         headers:
           accept: application/json
           Authorization: ApiKey <redacted>
         sample_exclude_filter:
           - cluster_name: dss-poc
           - cluster_name: ldap-test
           - cluster_name: workplace-search-poc
```

Based on the examples provided, it looks to be syntactically correct? I'm not sure what I am doing wrong?
Thank you,
Stephen
