### ISSUE TITLE
store_lookups: not parsing all values in subsequent call

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nri-flex#48]
I'm attempting to use the new "create lookups from plain arrays" feature in v0.8.6.  Below is the sample payload returned from the Burrow API that contains a consumers array.  

```
{
  "error": false,
  "message": "consumer list returned",
  "consumers": [
    "burrow-kafka-test",
    "test-group-1",
    "test-group-2"
  ],
  "request": {
    "url": "/v3/kafka/kafka-test/consumer",
    "host": "ubuntu-kafka"
  }
}
```

What I believe is happening though is that Flex is selecting the first item in the array and that's it.  In my query output, you can see there is only 1 event per group, per interval.  I would expect to see 3 events every minute.

![image](https://user-images.githubusercontent.com/9002169/71753099-1817f380-2e47-11ea-8d9c-20b5aaed9e6b.png)

Perhaps something isn't quite right in my config?  See below:

```
integrations:
  - name: nri-flex
    interval: 60s
    config:
      name: Burrow
      global:
        base_url: http://kafka1.abc.com:8000/v3/
      apis:
        - event_type: kafkaClusterNameSample
          url: kafka
          store_lookups:
            clusters: clusters
        - event_type: kafkaConsumerNameSample
          url: kafka/${lookup:clusters}/consumer
          store_lookups:
            consumers: consumers
        - event_type: kafkaConsumerGroupLagSample
          url: kafka/${lookup:clusters}/consumer/${lookup:consumers}/lag
          strip_keys:
            - status>partitions
          rename_keys:
            status.cluster: cluster
            status.group: group
            status.status: status
        - event_type: kafkaPartitionSample
          url: kafka/${lookup:clusters}/consumer/${lookup:consumers}/lag
          inherit_attributes: true
          start_key:
            - status
            - partitions
          rename_keys:
            parent.1.cluster: cluster
```
