### ISSUE TITLE
Error Configuring Flex Integration in AWS EKS

### ISSUE THREAD

**Issue by tushargudadhe30** [newrelic/nri-flex#548]
## Description
Hello Support,

We are currently migrating our Flex integrations from a Node-based application to container-based applications within our AWS EKS environment.

We have a local script that monitors and reports on database connections managed by the c3p0 connection pool in a Jetty server. This script generates JSON-formatted data compatible with monitoring tools such as New Relic Flex.

While configuring the Flex integration through a ConfigMap in the EKS environment, we encountered the following error in the `newrelic_agent.log`:

```
2025-01-29T11:54:16,444+0000 [12 1] com.newrelic.agent.extension.ExtensionService ERROR: Unable to parse extension. Check permissions on /usr/local/bin/extensions/nri-flex.yml. java.lang.IllegalArgumentException: Extensions must have a name 
```
Note: We have given the execute permissions to all users.

## Expected Behavior
We are attempting to replicate our existing Node-based setup in a containerized environment on AWS EKS. The goal is to invoke a script that outputs data in JSON format, which is then should be sent to New Relic via the Flex integration.

## Steps to Reproduce
I have been following the guide here: https://github.com/newrelic/nri-flex/blob/master/docs/basics/k8s_configure.md

The configuration we are trying to implement looks like this:
```
  nri-flex.yml: |
    integrations:
      - name: nri-flex
        config:
          name: C3P0
          apis:
            - event_type: C3P0Flex
              commands:
                - run: /usr/local/bin/jetty_c3p0_monitor.py
```

We are mounting the nri-flex integration within the `/usr/local/bin/extensions` directory, where the New Relic JAR file is located(/usr/local/bin/).

## Your Environment
Kubernetes Version: 1.31

Do you have any suggestions or workarounds?
Thank you for your assistance!
