### ISSUE TITLE
Duplicate executions/results as result of store_lookups

### ISSUE THREAD

**Issue by bokken** [newrelic/nri-flex#58]
I am using the following yml:

```
name: glusterVolumes
apis:
  - name: glusterVolumes
    commands:
      - run: gluster volume info | tail -n +2
        split_by: ": "
        split_output: ^\s*$ # regex to split by line
    convert_space: "_"
    snake_to_camel: true
    remove_keys:
      - ^brick.*$
    store_lookups:
      volumeName: volumeName
  - name: glusterPartitions
    commands:
              #strip first 2 lines; remove spaces separating keys and values; remove trailing spaces; remove word "Brick " in front of actual brick name
      - run: gluster volume status ${lookup:volumeName} detail | tail -n +3 | sed 's|\s\{1,\}:\s|:|g' | sed 's|\s\{1,\}$||g' | sed 's|:Brick |:|g'
        split_by: ":"
        split_output: ^--*$
    convert_space: "_"
    snake_to_camel: true
    custom_attributes:
      volumeName: ${lookup:volumeName}
```

The glusterVolumes command results in the following output:

```
Volume Name: partition000
Type: Replicate
Volume ID: c7d69ab4-4aec-4e74-a648-497774bfb449
Status: Started
...
diagnostics.client-log-level: WARNING

Volume Name: partition001
Type: Replicate
Volume ID: d5654ea6-04fc-43df-bb45-7f4145f632cb
Status: Started
...
diagnostics.client-log-level: WARNING
```

Which is 2 volumeName values: partition000 and partition001.

The glusterPartitions command for partition000 results in:

```
Brick:dwxvalgovgluster1:/mount/cps/dwxval_gov_gluster_p/partition000/dwxvalgovgluster1
TCP Port:49152
RDMA Port:0
Online:Y
...
Free Inodes:130968952
------------------------------------------------------------------------------
Brick:dwxvalgovgluster2:/mount/cps/dwxval_gov_gluster_p/partition000/dwxvalgovgluster2
TCP Port:49152
RDMA Port:0
Online:Y
...
Free Inodes:130968952
```

For partition001 the results are:

```
Brick:dwxvalgovgluster1:/mount/cps/dwxval_gov_gluster_p/partition001/dwxvalgovgluster1
TCP Port:49153
RDMA Port:0
Online:Y
...
Free Inodes:130969170
------------------------------------------------------------------------------
Brick:dwxvalgovgluster2:/mount/cps/dwxval_gov_gluster_p/partition001/dwxvalgovgluster2
TCP Port:49153
RDMA Port:0
Online:Y
...
Free Inodes:130969170
```

Based on this, I would expect the flex execution to result in 2 glusterVolumesSample events and 4 glusterPartitionsSample events. Strangely, however, I am getting 6 glusterPartitionsSample events.
I have attached the "pretty" json output from nri-flex. It is interesting that the flexStatusSample event confirms 6 partition samples:

```
					"flex.counter.ConfigsProcessed": 1,
					"flex.counter.EventCount": 8,
					"flex.counter.EventDropCount": 0,
					"flex.counter.glusterPartitionsSample": 6,
					"flex.counter.glusterVolumesSample": 2,
```

[pretty_json.txt](https://github.com/newrelic/nri-flex/files/4077427/pretty_json.txt)
